apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nextdns
spec:
  selector:
    matchLabels:
      app: nextdns
  template:
    metadata:
      labels:
        app: nextdns
    spec:
      hostNetwork: true
      containers:
        - name: nextdns
          image: ghcr.io/tecandrew/docker-nextdns:latest
          imagePullPolicy: Always
          env:
            - name: NEXTDNS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: nextdns-profile
                  key: profile1
            - name: NEXTDNS_SETUP_ROUTER
              value: "true"
            - name: NEXTDNS_REPORT_CLIENT_INFO
              value: "true"
            - name: NEXTDNS_MDNS
              value: "all"
            - name: NEXTDNS_MAX_INFLIGHT_REQUESTS
              value: "512"
            - name: NEXTDNS_CACHE_SIZE
              value: "10MB"
            - name: NEXTDNS_MAX_TTL
              value: "5s"
            - name: NEXTDNS_DEBUG
              value: "true"
            - name: NEXTDNS_LOG_QUERIES
              value: "true"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'dig +time=10 @127.0.0.1 -p $(echo ${NEXTDNS_LISTEN:-:53} | rev | cut -d: -f1 | rev) probe-test.dns.nextdns.io'
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 300
            timeoutSeconds: 3
          ports:
            - containerPort: 53
              hostPort: 53
              protocol: TCP
            - containerPort: 53
              hostPort: 53
              protocol: UDP
          resources: {}
      restartPolicy: Always
